### ISSUE TITLE
theme.css missing in waybar

### ISSUE THREAD

**Issue by gnussbaum67** [Anik200/dotfiles#1]
Waybar won't start as it's missing theme.css

**Comment by Anik200** [comment]
> Waybar won't start as it's missing theme.css
Oh hey 👋 thanks for using my dotfiles, it was an edited version on prasanthrangan's dotfiles until yesterday i made it completely independent.Please sync your `style.css` from the repository 
please let me know if it works :)

**Comment by tn3rb** [comment]
hi @Anik200 

thnx for sharing your dotfiles.
There's a new issue caused from removing the `theme.css` import in that now there are a bunch of missing variables in the `waybar/style.css` file with names like `@wb-color`

Do you happen to know what those were or where they came from?

Thanks for your time, effort, and talent.

**Comment by Anik200** [comment]
> hi @Anik200
> 
> thnx for sharing your dotfiles. There's a new issue caused from removing the `theme.css` import in that now there are a bunch of missing variables in the `waybar/style.css` file with names like `@wb-color`
> 
> Do you happen to know what those were or where they came from?
> 
> Thanks for your time, effort, and talent.

Yes, they were used as an import from a previously available file called `colors.css` however the current workaround dosent need colora for these elements you found the `wb-color`, you can either keep them or set them to transparent. Thanks for sharing the issue and i will clean up junk lines in the future updates.
