### ISSUE TITLE
installation script or steps on how to reproduce

### ISSUE THREAD

**Issue by MNkoder** [Anik200/dotfiles#2]
hey! it would be really cool if you could provide an installation script or step by step instructions on how to get your setup running :) ofcourse you dont need to.. but would be a great thing if you do!

**Comment by Anik200** [comment]
> hey! it would be really cool if you could provide an installation script or step by step instructions on how to get your setup running :) ofcourse you dont need to.. but would be a great thing if you do!

There is nothing much needed, install the dependencies i mentioned and copy the dotconfig folder to your $HOME/.config

**Comment by MNkoder** [comment]
> > hey! it would be really cool if you could provide an installation script or step by step instructions on how to get your setup running :) ofcourse you dont need to.. but would be a great thing if you do!
> 
> There is nothing much needed, install the dependencies i mentioned and copy the dotconfig folder to your $HOME/.config

thanks man, I'm sorry if I'm dumb but will I be getting the full setup if I install the packages and copy the configs? I saw in your readme to go to another acct for ags code? Is it for the bar? Like is it necessary?

**Comment by Anik200** [comment]
> > > hey! it would be really cool if you could provide an installation script or step by step instructions on how to get your setup running :) ofcourse you dont need to.. but would be a great thing if you do!
> > 
> > There is nothing much needed, install the dependencies i mentioned and copy the dotconfig folder to your $HOME/.config
> 
> thanks man, I'm sorry if I'm dumb but will I be getting the full setup if I install the packages and copy the configs? I saw in your readme to go to another acct for ags code? Is it for the bar? Like is it necessary?

Im using only the calender and the controll center (brightness,network,mic thing) but it comes with a bar you can use pr disable through the main javascript file
